### ISSUE TITLE
The recipes for the ultimate pickaxe and ultimate axe are switched 

### ISSUE THREAD

**Issue by Alexander317** [HuanMeng-official/RespawnEye#1]
![image](https://github.com/HuanMeng-official/RespawnEye/assets/139920415/aa38a240-a5d0-4e11-a240-bb22c3807349)
![image](https://github.com/HuanMeng-official/RespawnEye/assets/139920415/369be154-4a89-4953-bdde-8ee618fde073)

**Comment by HuanMeng-official** [comment]
I'm sorry to hear that. Can you tell me which version?
