### ISSUE TITLE
[NOT AN ISSUE] Adding image to modrinth page would be good

### ISSUE THREAD

**Issue by Hiusi** [HuanMeng-official/RespawnEye#2]
I feel like this mod doesn't get enough recognition, and maybe it's because lack of image used on the modpage, if you have spare time please upload some image to mod page

**Comment by HuanMeng-official** [comment]
Thank you for your suggestions, but this mod has not yet been developed. The most complete version is only the fabric version 1.20.4, so I will not add images for the time being. I wish you good luck.
